# Generated by Django 3.0.8 on 2020-11-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.TextField(max_length=15, null=True, verbose_name='phone'),
        ),
    ]
