# Generated by Django 3.0.8 on 2020-11-28 13:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('desc', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, default='', upload_to=main.models.path_and_rename)),
            ],
        ),
    ]
