# Generated by Django 3.0.8 on 2020-11-28 10:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201128_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=main.models.path_and_rename),
        ),
    ]
